spring.application.name=student

spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Obul6281@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhargav.sai29405@gmail.com
spring.mail.password=mlilnmyxxyacpuhk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=8080
logging.level.root=INFO
logging.level.org.springframework=Info
logging.level.org.hibernate=INFO
logging.level.studentcom.example.demo=INFO
logging.file.name=logs/studentapp.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n
